backend/modules/admin/controllers/PermissionController.php
<?php

namespace backend\modules\admin\controllers;

use backend\controllers\BaseController;
use backend\modules\admin\models\AuthItem;
use backend\modules\admin\models\AuthItemSearch;
use yii\bootstrap\ActiveForm;
use Yii;
use yii\db\ActiveRecord;
use yii\db\Exception;
use yii\web\Response;

class PermissionController extends BaseController
{
    /**
     * @return string
     */
    public function actionIndex(){
        $searchModel = new AuthItemSearch();
        $variable = new AuthItem();

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $variable::CATEGORY_PERMISSION);
        $model = AuthItem::find()->where(['type' => $variable::CATEGORY_PERMISSION])->all();

        return $this->render('permission_index', [
            'model' => $model,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @return array|string|Response
     */
    public function actionCreate(){

        $model = new AuthItem();

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = 'json';
            return ActiveForm::validate($model);
        }

        if ($model->load(Yii::$app->request->post())) {
            $children = $model->elements;
            if (!empty($children)) {
                $model->setAttributes([
                    'elements' => true,
                    'type' => $model::CATEGORY_PERMISSION,
                    'created_at' => strtotime(date('Y-m-d H:i:s')),
                    'updated_at' => strtotime(date('Y-m-d H:i:s'))
                ]);
                try {
                    $transaction = Yii::$app->db->beginTransaction();
                    $saved = false;
                    if ($model->save()) {
                        foreach ($children as $item) {
                            $permission = new AuthItem();
                            $permission->setAttributes([
                                'name' =>  $model->name . '/' . $item['name'],
                                'description' => NULL,
                                'type' => $model::PERMISSION,
                                'created_at' => strtotime(date('Y-m-d H:i:s')),
                                'updated_at' => strtotime(date('Y-m-d H:i:s')),
                                'elements' => true
                            ]);
                            if ($permission->save()) {
                                $saved = true;
                            } else {
                                $saved = false;
                                break;
                            }
                        }
                    }
                    if ($saved) {
                        $transaction->commit();
                        Yii::$app->session->set('success', Yii::t('app', 'Permission saved!'));
                    } else {
                        $transaction->rollBack();
                        Yii::$app->session->set('danger', Yii::t('app', 'Error saving permission!'));
                    }
                } catch (Exception $e){
                    Yii::info('Error Permission Saved '.$e->getMessage(),'save');
                }
            } else {
                Yii::$app->session->set('danger', Yii::t('app', 'Items not included!'));
            }
            return $this->redirect(['index']);
        }

        $model->elements = ['index', 'create', 'update', 'delete', 'view'];
        if (Yii::$app->request->isAjax) {
            return $this->renderAjax('permission_create', [
                'model' => $model,
            ]);
        }
        return $this->render('permission_create', [
            'model' => $model,
        ]);
    }

    /**
     * @param $id
     * @return array|string|Response
     */
    public function actionUpdate($id){

        $model = AuthItem::findOne(['name' => $id]);

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = 'json';
            return ActiveForm::validate($model);
        }

        if ($model->load(Yii::$app->request->post())) {
            $children = $model->elements;
            if (!empty($children)) {
                $model->setAttributes([
                    'elements' => true,
                    'type' => $model::CATEGORY_PERMISSION,
                    'created_at' => strtotime(date('Y-m-d H:i:s')),
                    'updated_at' => strtotime(date('Y-m-d H:i:s'))
                ]);

                try {
                    $transaction = Yii::$app->db->beginTransaction();
                    $saved = false;
                    if ($model->save()) {
                        foreach ($children as $item) {
                            $permission_name = $model->name . '/' . $item['name'];
                            $one = AuthItem::findOne(['name' => $permission_name]);
                            if (empty($one)) {
                                $permission = new AuthItem();
                                $permission->setAttributes([
                                    'name' => $permission_name,
                                    'description' => NULL,
                                    'type' => $model::PERMISSION,
                                    'elements' => true,
                                    'created_at' => strtotime(date('Y-m-d H:i:s')),
                                    'updated_at' => strtotime(date('Y-m-d H:i:s'))
                                ]);
                                if ($permission->save()) {
                                    $saved = true;
                                } else {
                                    $saved = false;
                                    break;
                                }
                            } else {
                                $saved = true;
                            }
                        }
                    }
                    if ($saved) {
                        $transaction->commit();
                        Yii::$app->session->set('success', Yii::t('app', 'Permission edited!'));
                    } else {
                        $transaction->rollBack();
                        Yii::$app->session->set('danger', Yii::t('app', 'Error editing permission!'));
                    }
                } catch (Exception $e){
                    Yii::info('Error Permission Update '.$e->getMessage(),'update');
                }
            } else {
                Yii::$app->session->set('danger', Yii::t('app', 'Items not included!'));
            }
            return $this->redirect(['index']);
        }

        $response = AuthItem::find()
            ->where(['like', 'name', $model->name.'/%', false])
            ->andWhere(['type' => '2'])
            ->asArray()->all();


        $elements = [];
        if (!empty($response)) {
            foreach ($response as $item) {
                if (strlen($model->name) == strrpos($item['name'], '/')) {
                    $item['name'] = strrev($item['name']);
                    $name = strstr($item['name'], '/', true);
                    array_push($elements, strrev($name));
                }
            }
            $model->elements = $elements;
        }
        if (Yii::$app->request->isAjax) {
            return $this->renderAjax('permission_update', [
                'model' => $model,
            ]);
        }

        return $this->render('permission_update', [
            'model' => $model,
        ]);
    }

    /**
     * @param $name
     * @return bool
     * @throws \Throwable
     * @throws yii\db\StaleObjectException
     */
    public function actionRemoveOneAjax($name){
        $permission = AuthItem::findOne(['name' => (string)$name]);
        if (!empty($permission)) {
           if ($permission->delete()) {
               return true;
           } else {
               return false;
           }
        }
        return true;
    }

    /**
     * @param $id
     * @return array|ActiveRecord[]
     * @throws \Throwable
     */
    public function actionRemove($id){
        $model = AuthItem::findOne($id);
        $name = $model->name.'/%';
        Yii::$app->response->format = Response::FORMAT_JSON;
        $response['status'] = 'false';
        $response['error'] = Yii::t('app', 'Error deleting permission!');
        $response['saved'] = Yii::t('app', 'Permission deleted!');
        $response['error_one'] = Yii::t('app', 'Deleted Error!');
        $response['saved_one'] = Yii::t('app', 'Deleted!');
        if (!empty($model) && $model->type == $model::CATEGORY_PERMISSION) {
            try {
                $transaction = Yii::$app->db->beginTransaction();
                $saved = false;
                if ($model->delete()) {
                    $saved = true;
                    $res = AuthItem::find()->where(['like', 'name', $name, false])->andWhere(['type' => '2'])->asArray()->all();
                    if (!empty($res)) {
                        foreach ($res as $item) {
                            if (strlen($name)-2 == strrpos($item['name'], '/')) {
                                AuthItem::deleteAll(['name' => $item['name']]);
                            }
                        }
                    }
                }
                if ($saved) {
                    $transaction->commit();
                    $response['status'] = 'true';
                } else {
                    $transaction->rollBack();
                    $response['status'] = 'false';
                }
            } catch (Exception $e){
                Yii::info('Error Permission Deleted'.$e->getMessage(),'delete');
            }
        }
        return $response;
    }
}

backend/modules/admin/views/permission/_permission.php
<?php

use common\components\TabularInput\CustomMultipleInput;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\modules\admin\models\AuthItem */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="col-xxl-8 order-2 order-xxl-1">
    <div class="card card-custom card-stretch gutter-b">
        <div class="card-body pt-4 pb-1 pl-4 pr-4">
            <?php $form = ActiveForm::begin([
                'enableAjaxValidation' => true,
            ]); ?>
            <div class="row">

                <div class="col-sm-6">
                    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
                </div>

                <div class="col-sm-6">
                    <?= $form->field($model, 'description')->textInput(['maxlength' => true]) ?>
                </div>

                <div class="col-sm-12">
                    <?= $form->field($model, 'elements')->widget(CustomMultipleInput::className(), [
                        'removeButtonOptions' => ['class' => 'btn btn-danger btn-input remove-button-click'],
                        'addButtonOptions' => ['class' => 'btn btn-primary btn-input'],
                        'theme' => CustomMultipleInput::THEME_BS,
                        'id' => 'form',
                        'columns' => [
                            [
                                'name' => 'name',
                                'type' => 'textinput',
                                'title' => Yii::t('app', 'Name Items'),
                            ],
                            [
                                'name' => 'description',
                                'type' => 'textinput',
                                'title' => Yii::t('app', 'Description Items'),
                            ],
                        ]
                    ])->label(false); ?>
                </div>

                <div class="col-sm-12 mb-4">
                    <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success btn-sm saveButton btn-save']) ?>
                </div>

            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>
<?php
$url = \yii\helpers\Url::to(['permission/remove-one-ajax']);
$js = <<<JS
    var name = $('#authitem-name').val();
    jQuery('#w1').on('beforeDeleteRow',function(e, row,currentIndex) {
       let inputName = name + '/' + row.find(':input').val();
       $.ajax({
           url: '$url',
           data: {name: inputName},
           type: 'GET',
           success: function (res) {
               console.log(res);
           }
       });
    });
JS;

$this->registerJs($js, \yii\web\View::POS_READY);

backend/modules/admin/views/permission/permission_create.php
<?php

/* @var $this yii\web\View */
/* @var $model backend\modules\admin\models\AuthItem */
/* @var $permission_category backend\modules\admin\models\AuthItem */

$this->title = Yii::t('app', 'Create Permission');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Permission'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<?= $this->render('_permission', [
    'model' => $model,
]) ?>

backend/modules/admin/views/permission/permission_index.php
<?php

use backend\modules\admin\models\AuthItem;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\modules\admin\models\AuthItemSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Permission');
$this->params['breadcrumbs'][] = $this->title;
?>


<?php Modal::begin([
    'header' => '',
    'size' => 'modal-lg',
    'id' => 'exampleModalSizeLg'
]) ?>
    <div id="modal-body"></div>

<?php Modal::end() ?>

    <div class="col-12 layout-spacing mt-2">
        <div class="widget widget-chart-one">
            <div class="widget-heading">
                <?= Html::a(Yii::t('app', 'Create Permission'), ['create'], ['class' => 'btn btn-primary btn-sm button-modal-show', 'data-toggle' => "modal", 'data-target' => "#exampleModalSizeLg"]); ?>
            </div>
            <div class="widget-content">
                <div class="table-responsive">
                    <?php
                    echo GridView::widget([
                        'dataProvider' => $dataProvider,
                        'filterModel' => $searchModel,
                        'tableOptions' => ['class' => 'table table-bordered'],
                        'columns' => [
                            ['class' => 'yii\grid\SerialColumn'],

                            [
                                'attribute' => 'name',
                                'label' => Yii::t('app', 'Permission Category'),
                            ],
                            [
                                'attribute' => 'children',
                                'headerOptions' => ['style' => 'color: #1b55e2;'],
                                'label' => Yii::t('app', 'Permissions'),
                                'options' => ['style' => 'width: 50%'],
                                'format' => 'raw',
                                'value' => function ($model) {
                                    return AuthItem::getChildrenPermissionCategory($model->name);
                                }
                            ],
                            [
                                'class' => 'yii\grid\ActionColumn',
                                'template' => '{update} {remove}',
                                'header' => Yii::t('app', 'Actions'),
                                'headerOptions' => ['class' => 'text-center', 'style' => 'color: #1b55e2;'],
                                'contentOptions' => ['style' => 'width: 70px!important'],
                                'buttons' => [
                                    'update' => function ($url) {
                                        return Html::a('<i class="glyphicon glyphicon-edit"></i>', $url, [
                                            'title' => Yii::t('app', 'Update'),
                                            'class' => "btn btn-sm btn-info button-modal-show",
                                            'data-toggle' => "modal", 'data-target' => "#exampleModalSizeLg"
                                        ]);
                                    },
                                    'remove' => function ($url) {
                                        return Html::a('<i class="glyphicon glyphicon-trash"></i>', $url, [
                                            'title' => Yii::t('app', 'Delete'),
                                            'class' => "btn btn-sm btn-danger delete-button-ajax",
                                        ]);
                                    },

                                ],
//                                    'visibleButtons' => [
//                                        'update' => function () {
//                                            return Yii::$app->user->can('permission/update');
//                                        },
//                                        'remove' => function () {
//                                            return Yii::$app->user->can('permission/delete');
//                                        },
//                                    ],
                            ],
                        ]
                    ]);
                    ?>
                </div>
            </div>
        </div>
    </div>
<?php
$js = <<<JS
    $('.button-modal-show').click(function(e){
        e.preventDefault();
        let url = $(this).attr('href');
        $('.modal-body').load(url);
         setTimeout(function (){
             $('.modal-title').html('$this->title');
         }, 1000);
    });
JS;
$this->registerJs($js);

backend/modules/admin/views/permission/permission_update.php
<?php

/* @var $this yii\web\View */
/* @var $model backend\modules\admin\models\AuthItem */
/* @var $permission_category backend\modules\admin\models\AuthItem */

$this->title = Yii::t('app', 'Update Permission');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Permission'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<?= $this->render('_permission', [
    'model' => $model,
]) ?>